name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
  
    - name: Install dependencies (ultralytics ＆ Nuitka)
      run: |
        python -m pip install --upgrade pip
        pip install ultralytics nuitka

    - name: Build with Nuitka
      run: |
        python -m nuitka --assume-yes-for-downloads --mingw64 --remove-output --standalone --enable-plugin=no-qt --include-data-files="default.yaml=ultralytics/cfg/default.yaml" --output-dir=dist Module_detect.py

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: dist/
